name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7']
        aw-server: ["aw-server", "aw-server-rust"]
        aw-version: ["v0.10.0"]
        include:
        - aw-server: "aw-server-rust"
          aw-version: "master"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up ActivityWatch
      uses: ActivityWatch/setup-action@v0
      with:
        aw-server: ${{ matrix.aw-server }}
        aw-version: ${{ matrix.aw-version }}
        aw-testing: ${{ matrix.aw-testing }}
        fakedata: true
